name: Windows build and tests
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: windows-2025
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1, Node.js 24
      - name: Build and test
        shell: pwsh
        run: ./scripts/Build.ps1 -Configuration Release
